apiVersion: v1
kind: Service
metadata:
  name: wings-prometheus-monitoring
  namespace: monitoring
spec:
  selector:
    app: wings-monitoring
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
